[package]
name = "pyext-myrustlib"
version = "0.2.0"
authors = ["Daniel Naschberger <daniel@naschi.at>"]
edition = "2021"

[lib]
name = "myrustlib"
crate-type = ["cdylib"]

[dependencies.cpython]
version = "0.7"
features = ["extension-module"]